/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package course.project;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author support
 */
public class ClientGUI extends javax.swing.JFrame {
    
    private static LoanServerInterface obj;
    private double loanAmount;
    private String currency;
    private double numberOfYears;
    private double interestRate;
    private double monthlyPmt;

    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainContainer = new javax.swing.JPanel();
        OptionsContainer = new javax.swing.JPanel();
        InterestRateLabel = new javax.swing.JLabel();
        InterestRateTxtField = new javax.swing.JTextField();
        NumberOfYearsLabel = new javax.swing.JLabel();
        NumberOfYearsTxtField = new javax.swing.JTextField();
        LoanAmountLabel = new javax.swing.JLabel();
        LoanAmountTxtField = new javax.swing.JTextField();
        CurrencyLabel = new javax.swing.JLabel();
        CurrencyComboBox = new javax.swing.JComboBox();
        SubmitButton = new javax.swing.JButton();
        InformationPane = new javax.swing.JScrollPane();
        InfoPanel = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        MainContainer.setLayout(new javax.swing.BoxLayout(MainContainer, javax.swing.BoxLayout.LINE_AXIS));

        OptionsContainer.setLayout(new java.awt.GridLayout(4, 2));

        InterestRateLabel.setText("Annual Interest Rate");
        OptionsContainer.add(InterestRateLabel);
        OptionsContainer.add(InterestRateTxtField);

        NumberOfYearsLabel.setText("Number of years");
        OptionsContainer.add(NumberOfYearsLabel);
        OptionsContainer.add(NumberOfYearsTxtField);

        LoanAmountLabel.setText("Loan Amount");
        OptionsContainer.add(LoanAmountLabel);
        OptionsContainer.add(LoanAmountTxtField);

        CurrencyLabel.setText("Currency");
        OptionsContainer.add(CurrencyLabel);

        CurrencyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BGN", "USD", "EURO", "RUB", "AUD", "ZAR", "CYN", "TRY" }));
        CurrencyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyComboBoxActionPerformed(evt);
            }
        });
        OptionsContainer.add(CurrencyComboBox);

        MainContainer.add(OptionsContainer);

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        MainContainer.add(SubmitButton);

        getContentPane().add(MainContainer);

        InfoPanel.setEditable(false);
        InformationPane.setViewportView(InfoPanel);

        getContentPane().add(InformationPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CurrencyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrencyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrencyComboBoxActionPerformed
    
    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        try {
            loanAmount = Double.parseDouble(LoanAmountTxtField.getText());
            numberOfYears = Double.parseDouble(NumberOfYearsTxtField.getText());
            interestRate = Double.parseDouble(InterestRateTxtField.getText());
            currency = CurrencyComboBox.getItemAt(CurrencyComboBox.getSelectedIndex()).toString();
            monthlyPmt = obj.calculateMonthlyPayment(loanAmount, numberOfYears,
                    interestRate, currency);
            InfoPanel.setText(String.format("Annual Interest Rate: %.2f, Number of years:%.2f, Loan Amount: %.2f %s, monthly payment in BGN: %.2f", interestRate, numberOfYears, loanAmount, currency, monthlyPmt));
            
        } catch (RemoteException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Registry registry;
        try {
            registry = LocateRegistry.getRegistry(1099);
            obj = (LoanServerInterface) registry.lookup("LoanServerInterface");
        } catch (RemoteException | NotBoundException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CurrencyComboBox;
    private javax.swing.JLabel CurrencyLabel;
    private javax.swing.JTextPane InfoPanel;
    private javax.swing.JScrollPane InformationPane;
    private javax.swing.JLabel InterestRateLabel;
    private javax.swing.JTextField InterestRateTxtField;
    private javax.swing.JLabel LoanAmountLabel;
    private javax.swing.JTextField LoanAmountTxtField;
    private javax.swing.JPanel MainContainer;
    private javax.swing.JLabel NumberOfYearsLabel;
    private javax.swing.JTextField NumberOfYearsTxtField;
    private javax.swing.JPanel OptionsContainer;
    private javax.swing.JButton SubmitButton;
    // End of variables declaration//GEN-END:variables
}
